purpose: []
color:
  saturation: 0.5
  brandStrength: 0.7731872
  rhythmicContrast: 0.25
  brandColors:
    - '#0B0804'
    - '#FFFFFF'
    - '#884719'
    - '#A09292'
    - '#F4D0B5'
  lightness: 0.9375
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'Adagio Studios '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8575042
layout_spectrum: 1
