name: 'Adagio Studios '
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.49294
color:
  saturation: 0.5
  brandStrength: 0.7731872
  rhythmicContrast: 0.25
  brandColors:
    - '#0B0804'
    - '#FFFFFF'
    - '#884719'
    - '#A09292'
    - '#F4D0B5'
  lightness: 0.9375
purpose: []
cta:
  bucket: null
  version: null
  domain: null
favicon: null
typography_spectrum: 0.8634064
analytics:
  twitter: null
  google: null
  facebook: null
